name: "z Slack Notify"

on:
  workflow_dispatch:

jobs:
  notify:
    name: Slack Notify
    runs-on: ubuntu-latest
    steps:
      - name: Slack notify
        uses: slackapi/slack-github-action@v2.0.0
        with:
          channel-id: "C08AUTFD9PX"
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Message Header",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Hello World :ghost:"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}