name: "z Slack Notify"

on:
  workflow_dispatch:

jobs:
  notify:
    name: Slack Notify
    runs-on: ubuntu-latest
    steps:
      - name: Slack notify
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          payload: |
            channel: 'C08AUTFD9PX'
            blocks: [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "Message Header",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Hello World :ghost:"
                }
              }
            ]
          token: ${{ secrets.SLACK_BOT_TOKEN }}